### ISSUE TITLE
Dates shown are different than actual yml. Why ?

### ISSUE THREAD

**Issue by macvfx** [finspin/gotodevops.org#63] opened 2018-12-21 05:20 UTC
Why are the dates listed as June 11-13 for MacDevOps:YVR when in the conference.yml the dates are set correctly as June 12-14? I cloned the repo to change the dates when I noticed they are correct. Just wondering why they are displayed differently?

**Comment by finspin** [comment] 2018-12-30 18:05
Thanks for reporting this. I _think_ it should be fixed now but it's bit hard for me to verify because I couldn't reproduce the original issue. It's related to timezones.

Could you please confirm that you see the correct dates now?

**Comment by macvfx** [comment] 2018-12-31 03:04
I see the correct dates now. Thanks.

**Comment by finspin** [comment] 2018-12-31 15:06
Great, thanks!

**Closed by finspin** 2018-12-31 15:06 UTC
Labels: bug
